"use strict";
// conditional test: True Or False
let fruit = "Mango";
let laptop = "MacBook";
let car = "Revo";
let flower = "Jasmine";
let currency = "$";
console.log("is fruit !== 'mango'I predict true");
console.log(fruit !== 'mango');
console.log("is fruit === 'Stawberry'I predict false");
console.log(fruit === 'Stawberry');
console.log("is laptop === 'M2'I predict false");
console.log(fruit === 'M2');
console.log("is laptop === 'MacBook'I predict true");
console.log(laptop === 'MacBook');
console.log("is car !== 'revo'I predict true");
console.log(car !== 'revo');
console.log("is car =='corolla'I predict false");
console.log(car == 'corolla');
console.log("is flower == 'Jasmine'I predict true");
console.log(flower == 'Jasmine');
console.log("is flower !== 'Jasmine'I predict false");
console.log(flower !== 'Jasmine');
console.log("is currency == 'Rs'I predict false");
console.log(currency == 'Rs');
console.log("is currency !== 'KWD'I predict true");
console.log(currency !== 'KWD');
